### ISSUE TITLE
Possible use with `trio`?

### ISSUE THREAD

**Issue by hanztura** [W1ndst0rm/Treillage#21]
We are currently implementing `trio` with a project that uses Treillage to make API calls to Filevine.

We've bumped into this problem:

```python
  Traceback (most recent call last):
    File "/Users/someuser/Projects/somecompany/projectrepo/skills/async_otherapi_filevine.py", line 69, in sync_expenses
      response = await filevine.api_update_form(
    File "/Users/someuser/Projects/somecompany/projectrepo/api/filevine.py", line 76, in api_update_form
      tr = await get_new_tr(ctx)
    File "/Users/someuser/Projects/somecompany/projectrepo/api/filevine.py", line 170, in get_new_tr
      return await async_load_tr(ctx)
    File "/Users/someuser/Projects/somecompany/projectrepo/api/filevine.py", line 161, in async_load_tr
      return await Treillage.create(credentials_file=f.name, base_url=base_url)
    File "/Users/someuser/Projects/somecompany/projectrepo/env/lib/python3.9/site-packages/treillage/treillage.py", line 59, in create
      await self.__async_init()
    File "/Users/someuser/Projects/somecompany/projectrepo/env/lib/python3.9/site-packages/treillage/treillage.py", line 37, in __async_init
      self.__conn = await ConnectionManager.create(
    File "/Users/someuser/Projects/somecompany/projectrepo/env/lib/python3.9/site-packages/treillage/connection_manager.py", line 74, in create
      self.__auth_tokens = await TokenManager.create(credentials, base_url)
    File "/Users/someuser/Projects/somecompany/projectrepo/env/lib/python3.9/site-packages/treillage/token_manager.py", line 32, in create
      await self.__request_tokens(request_type=TokenRequestType.KEY)
    File "/Users/someuser/Projects/somecompany/projectrepo/env/lib/python3.9/site-packages/treillage/token_manager.py", line 93, in __request_tokens
      await asyncio.sleep(0.250)
    File "/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/tasks.py", line 652, in sleep
      return await future
  TypeError: trio.run received unrecognized yield message <Future pending>. Are you trying to use a library written for some other framework like asyncio? That won't work without some kind of compatibility shim.
```

Would love to know if you guys have used `trio` with Treillage before?

We tried customizing Treillage with [trio-asyncio](https://github.com/python-trio/trio-asyncio) instead of `asyncio` but weren't successful.

**Comment by W1ndst0rm** [comment]
You're first I've heard using `trio` with Treillage. I'm not personally familiar with `trio`. I tried some quick sandboxing with `trio-asyncio`, and it seemed to work fine. I think the challenge will be integrating it into your larger project. Here's the code I tried:
```from treillage import Treillage
import trio_asyncio

async def async_main():
    async with Treillage("creds.yml") as treillage:
        pass

trio_asyncio.run(trio_asyncio.aio_as_trio(async_main))
```

**Comment by hanztura** [comment]
Awesome, thanks a lot @W1ndst0rm. I'll give it a shot.

**Comment by hanztura** [comment]
It unfortunately still didn't work in our case.

I've done `trio_asyncio.run(trio_asyncio.aio_as_trio(async_main))` but got this error:

```python
Traceback (most recent call last):
  File "/Users/someuser/Projects/somecompany/projectrepo/skills/async_otherapi_filevine.py", line 110, in nightly
    nursery.start_soon(async_filevine.sync, ctx, exclude_archived)
  File "/Users/someuser/Projects/somecompany/projectrepo/env/lib/python3.9/site-packages/trio/_core/_run.py", line 800, in __aexit__
    new_exc = await self._nursery._nested_child_finished(exc)
  File "/Users/someuser/Projects/somecompany/projectrepo/env/lib/python3.9/site-packages/trio/_core/_run.py", line 928, in _nested_child_finished
    await wait_task_rescheduled(aborted)
  File "/Users/someuser/Projects/somecompany/projectrepo/env/lib/python3.9/site-packages/trio/_core/_traps.py", line 166, in wait_task_rescheduled
    return (await _async_yield(WaitTaskRescheduled(abort_func))).unwrap()
  File "/Users/someuser/Projects/somecompany/projectrepo/env/lib/python3.9/site-packages/trio/_core/_traps.py", line 21, in _async_yield
    return (yield obj)
RuntimeError: Task got bad yield: WaitTaskRescheduled(abort_func=<function Nursery._nested_child_finished.<locals>.aborted at 0x10749a8b0>)
```

So subsequent calls from `async_main` we used trio's `nursery`. I'm not sure if that causes the problem.
